<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="meedo74-ThinkPad-X230" failures="1" tests="1" name=" making order " time="4.294" errors="0" timestamp="2024-01-22T00:08:53 EET">
  <testcase classname="testcases.T04_make_order" name="making_order_with_blocking_scenraio" time="2.4">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://www.saucedemo.com/checkout-step-two.html] but found [https://www.saucedemo.com/checkout-step-one.html]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.saucedemo.com/checkout-step-two.html] but found [https://www.saucedemo.com/checkout-step-one.html]
at testcases.T04_make_order.making_order_with_blocking_scenraio(T04_make_order.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- making_order_with_blocking_scenraio -->
</testsuite> <!--  making order  -->
